export const UPLOAD_CREDITS_RESET = 'UPLOAD_CREDITS_RESET'

export const UPLOAD_CREDITS_CHANGE_DELIMITER = 'UPLOAD_CREDITS_CHANGE_DELIMITER'

export const UPLOAD_CREDITS_CHANGE_FILE = 'UPLOAD_CREDITS_CHANGE_FILE'

export const UPLOAD_CREDITS_CHANGE_CREDITS = 'UPLOAD_CREDITS_CHANGE_CREDITS'

export const USER_PARSE_USER = 'USER_PARSE_USER'

export const USER_LOG_OUT = 'USER_LOG_OUT'

export const TOAST = 'TOAST'

export const SUBMISSION_STUDENT_GET_ALL = 'SUBMISSION_STUDENT_GET_ALL'

export const SUBMISSION_CREATE = 'SUBMISSION_CREATE'

export const SEARCH_SUBMISSION_CHANGE_INPUT = 'SEARCH_SUBMISSION_CHANGE_INPUT'

export const SEARCH_SUBMISSION_SUBMIT_ATTEMPT = 'SEARCH_SUBMISSION_SUBMIT_ATTEMPT'

export const SEARCH_SUBMISSION_SUBMIT_SUCCESS = 'SEARCH_SUBMISSION_SUBMIT_SUCCESS'

export const SEARCH_USER_CHANGE_INPUT = 'SEARCH_USER_CHANGE_INPUT'

export const SEARCH_USER_SUBMIT_ATTEMPT = 'SEARCH_USER_SUBMIT_ATTEMPT'

export const SEARCH_USER_SUBMIT_SUCCESS = 'SEARCH_USER_SUBMIT_SUCCESS'

export const USER_EDIT_ATTEMPT = 'USER_EDIT_ATTEMPT'

export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS'
