export const USER_PARSE_USER = 'USER_PARSE_USER'

export const USER_LOG_OUT = 'USER_LOG_OUT'

export const TOAST = 'TOAST'

export const STUDENT_GET_ME = 'STUDENT_GET_ME'

export const SUBMISSION_CREATE = 'SUBMISSION_CREATE'

export const SEARCH_SUBMISSION_CHANGE_INPUT = 'SEARCH_SUBMISSION_CHANGE_INPUT'

export const SEARCH_SUBMISSION_SUCCESS = 'SEARCH_SUBMISSION_SUCCESS'

export const SEARCH_USER_CHANGE_INPUT = 'SEARCH_USER_CHANGE_INPUT'

export const SEARCH_USER_SUBMIT_ATTEMPT = 'SEARCH_USER_SUBMIT_ATTEMPT'

export const SEARCH_USER_SUBMIT_SUCCESS = 'SEARCH_USER_SUBMIT_SUCCESS'

export const USER_EDIT_ATTEMPT = 'USER_EDIT_ATTEMPT'

export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS'

export const SEARCH_SUBMISSION_APPROVE_SUBMISSION_SUCCESS = 'SEARCH_SUBMISSION_APPROVE_SUBMISSION_SUCCESS'
