sudo: required
dist: trusty
notifications:
  email: false
language: node_js
node_js:
  - '8'
before_install:
  - npm install -g npm
jobs:
  include:
    - stage: tests
      cache:
        directories:
          - frontend/node_modules
      install:
        - cd frontend
        - npm install
      script:
        - npm run lint
    - stage: tests
      cache:
        directories:
          - backend/node_modules
      install:
        - cd backend
        - npm install
      script:
        - npm run lint
