sudo: required
dist: trusty
notifications:
  email: false
language: node_js
node_js:
  - '8'
services:
 - docker
before_install:
  - npm install -g npm
jobs:
  include:
    - stage: tests
      cache:
        directories:
          - frontend/node_modules
      install:
        - cd frontend
        - npm install
      script:
        - npm test
        - npm run lint
    - stage: tests
      cache:
        directories:
          - backend/node_modules
      before_install:
        - >
            printf "version: '2'\nservices:\n    mongodb:\n        image: mongo:latest\n        container_name: "mongodb"\n        environment:\n          - MONGO_INITDB_ROOT_USERNAME=travis\n          - MONGO_INITDB_ROOT_PASSWORD=travispass\n          - MONGO_INITDB_DATABASE=db\n          - MONGO_DATA_DIR=/data/db\n          - MONGO_LOG_DIR=/dev/null\n        volumes:\n          - ./data/db:/data/db\n        ports:\n            - 27017:27017\n        command: mongod --smallfiles --logpath=/dev/null" >> docker-compose.yml
        - docker-compose up -d
      install:
        - cd backend
        - npm install
      script:
        - npm run test-ci
        - npm run lint
      env:
        - DATABASE_URI=localhost:27017
        - DATABASE_USER=travis
        - DATABASE_PASS=travispass
        - TEST_DATABASE_NAME=test
        - SECRET=long0string1of2random3alphanumerical4characters5
        - FRONTEND_LOGIN=http://localhost:8080/login
    - stage: build & deploy
      script:
        - cd ../frontend
        - printf "API_URL=$API_URL\nLOGIN_URL=$LOGIN_URL\nDS_URL=$DS_URL\nENTITY_ID=$ENTITY_ID" > .env
        - "if [[ $TRAVIS_BRANCH =~ (^master) ]]; && docker build -t toska/defa-frontend:staging . ; else :; fi"
        - "if [[ $TRAVIS_BRANCH =~ (^master) ]]; && docker login -u $DOCKER_USER -p $DOCKER_PASS ; else :; fi"
        - "if [[ $TRAVIS_BRANCH =~ (^master) ]]; && docker push toska/defa-frontend:staging ; else :; fi"
        - printf "API_URL=$PROD_API_URL\nLOGIN_URL=$PROD_LOGIN_URL\nDS_URL=$PROD_DS_URL\nENTITY_ID=$PROD_ENTITY_ID" > .env
        - "if [[ $TRAVIS_TAG =~ ([0-1].+) ]]; && docker build -t toska/defa-frontend:latest . ; else :; fi"
        - "if [[ $TRAVIS_TAG =~ ([0-1].+) ]]; && docker login -u $DOCKER_USER -p $DOCKER_PASS ; else :; fi"
        - "if [[ $TRAVIS_TAG =~ ([0-1].+) ]]; && docker push toska/defa-frontend:latest ; else :; fi"
        - rm .env
        - cd ../backend
        - "if [[ $TRAVIS_BRANCH =~ (^master) ]]; && docker build -t toska/defa-backend:staging . ; else :; fi"
        - "if [[ $TRAVIS_BRANCH =~ (^master) ]]; && docker login -u $DOCKER_USER -p $DOCKER_PASS ; else :; fi"
        - "if [[ $TRAVIS_BRANCH =~ (^master) ]]; && docker push toska/defa-backend:staging ; else :; fi"
        - "if [[ $TRAVIS_TAG =~ ([0-1].+) ]]; && docker build -t toska/defa-backend:latest . ; else :; fi"
        - "if [[ $TRAVIS_TAG =~ ([0-1].+) ]]; && docker login -u $DOCKER_USER -p $DOCKER_PASS ; else :; fi"
        - "if [[ $TRAVIS_TAG =~ ([0-1].+) ]]; && docker push toska/defa-backend:latest ; else :; fi"
        - cd ../graphql-backend
        - "if [[ $TRAVIS_BRANCH =~ (^master) ]]; && docker build -t toska/defa-graphql-backend:staging . ; else :; fi"
        - "if [[ $TRAVIS_BRANCH =~ (^master) ]]; && docker login -u $DOCKER_USER -p $DOCKER_PASS ; else :; fi"
        - "if [[ $TRAVIS_BRANCH =~ (^master) ]]; && docker push toska/defa-graphql-backend:staging ; else :; fi"
        - "if [[ $TRAVIS_TAG =~ ([0-1].+) ]]; && docker build -t toska/defa-graphql-backend:latest . ; else :; fi"
        - "if [[ $TRAVIS_TAG =~ ([0-1].+) ]]; && docker login -u $DOCKER_USER -p $DOCKER_PASS ; else :; fi"
        - "if [[ $TRAVIS_TAG =~ ([0-1].+) ]]; && docker push toska/defa-graphql-backend:latest ; else :; fi"
        - cd ../idp
        - "if [[ $TRAVIS_BRANCH =~ (^master) ]]; && docker build -t toska/defa-backend:idp . ; else :; fi"
        - "if [[ $TRAVIS_BRANCH =~ (^master) ]]; && docker login -u $DOCKER_USER -p $DOCKER_PASS ; else :; fi"
        - "if [[ $TRAVIS_BRANCH =~ (^master) ]]; && docker push toska/defa-backend:idp ; else :; fi"
